config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "users/sessions" }

  root 'welcome#index'

  resources :welcome do
  end

  get '/evaluate' =>'welcome#evaluate'

  namespace :admin do
    resources :unbusys
  end

  get '/about' =>'welcome#about'

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

    post "/signup" => "auth#signup"

    resources :bookings

    post "/checkout_pay2go" => "bookings#checkout_pay2go"
    get '/about' => 'welcome#about'

  end

  post 'pay2go/return' # returnURL是Pay2go通知使用者付款成功
  post 'pay2go/notify' # notifyURL是Pay2go用來通知店家後台交易結果的URL

  resources :users do
    resource :profile
  end
  resources :bookings do
    member do
      post :checkout_pay2go
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render layout: "indexonly"
  end

  def about
  end

  def evaluate
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div id="about-page">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <p>主旨：感謝您支持 不忙按摩!!</p>

        <p>--</p>

        <p>您好，</p>

        <p>
          歡迎您加入「不忙按摩」的行列。</br>
          我們關心您和您的團隊的健康，希望透過最簡單的方式，讓專業的按摩師傅能夠到您的公司為您的團隊服務，您只需要準備適合的空間(小會議室或3x3m<sup>2</sup>左右的大小)，並告訴我們想邀請的按摩師人數，其他事情，我們都會幫您準備好。</br>
          在您的團隊享受按摩的同時，我們會用照片記錄下這個美好的時光，並且在按摩之後簡單聊聊這個新奇的體驗，相關的文字和圖片會再彙整提供給您，作為公司形象曝光的素材以及員工內部的小小溫馨回憶，附件檔案室我們幫其他公司做的小記錄，提供給您參考。</br>
          我們的計費方式很簡單，每個按摩師出勤以三小時為一個單位，一位按摩師2,760元，再加上按摩師的交通費補貼，以台北市來說的話，大約是3,060元左右。</br>
          我們的系統還在建置中，預計在一個月左右就能上線，為了感謝您的支持，我們將贈送您100元的折價優惠，希望在不久的將來，能夠有機會為您服務。</br>
          如有任何問題，也歡迎您再與我們聯絡。</br>
          謝謝！
        </p>

        <br />

        <p>祝 一切順心</p>

        <p>Jade</br>
           不忙按摩 CEO</p>

      </div>
    </div>

  </div>
</div>

app/views/welcome/evaluate.html.erb
<div id="evaluation">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <h2>各方評價</h2>

        <div class="customerssay">
          <div class="col-sm-6">
            <h3>2016.04.25 ALPHA Camp</h3>
            <%= image_tag("picture-composed.png", size: "377x371") %>
          </div>

          <div class="col-sm-6">
            <p>今天不忙按摩來到新創人才的搖籃 Alphacamp 來幫這些經世濟民的熱血工程師們好好放鬆一下!! </br>
               一把扛起改變世界夢想的肩膀，果然是相當"堅硬"的啊
            </p>

            <%= link_to "ALPHA Camp 官方網站", "https://www.alphacamp.co/" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="index-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if user_signed_in? %>
                <%= link_to "登出", destroy_user_session_path, :method => :delete %>
              <% end %>
            </li>
            <li>
              <% if current_user && current_user.admin? %>
                <%= link_to "管理員", welcome_index_path %>
              <% end  %>
            </li>
            <li>
              <%= link_to "服務說明", about_path %>
            </li>
            <li>
              <%= link_to "各方評價", evaluate_path %>
            </li>
            <li>
              <% if user_signed_in? %>
                <%= link_to "預約查詢", user_path(current_user) %>
              <% else %>
                <%= link_to "預約查詢", user_session_path(:look_bookings => true) %>
              <% end %>
            </li>
            <li>
              <%= link_to '預約按摩', new_booking_path, :class =>"header_booking" %>
            </li>
          </ul>
        </div>

        <div class="content">
          <div class="logo">
            <%= image_tag("Logo.png") %>
          </div>

          <div class="vision">
            <p>線上預約專業的視障按摩服務，</br>
               讓您的專業團隊享有一流企業的美好福利
            </p>
          </div>

          <div class="service">
            <a class="booking" href="http://homepage.unbusymassage.tech/bookings/new" class="button">立即預約</a>
            <a class="download" href="#" class="button">下載預約App</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div id="specialty">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="title">
          <h2>我們的特色</h2>
        </div>

        <div class="col-sm-6">
          <%= image_tag("specialty-structure.png", :alt => "不忙按摩", :class => "image")%>
        </div>

        <div class="col-sm-6">
          <div class="introduction">
            <h3>良好的按摩體驗</h3>
            <p>政府認證的專業按摩師，用最有效率的方式幫您抒壓保健、提神醒腦，讓團隊活力滿點。</p>

            <h3>簡單的預約流程</h3>
            <p>用電腦、手機都可以完成預約，線上付款、確認預約，替您省去繁雜的聯絡程序，迅速搞定。</p>

            <h3>完善的服務內容</h3>
            <p>到您的公司為您服務，您只需要準備場地，器材、人員接送等其他事務，交給我們搞定。</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div id="flow">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="title">
          <h2>服務流程</h2>
        </div>

        <div class="col-md-3">
          <%= image_tag("服務流程行事曆圖.png", :alt => "不忙按摩")%>
          <h3>1. 決定時間與人數</h3>
          <p>挑選想要的時段和按摩師人數，系統會自動報價供您參考</p>
        </div>

        <div class="col-md-3">
          <%= image_tag("服務流程鉛筆圖.png", :alt => "不忙按摩")%>
          <h3>2. 填寫資料</h3>
          <p>填寫公司與聯絡資料，讓專業的按摩團隊能在之後順利前往您的鷹巢！</p>
        </div>

        <div class="col-md-3">
          <%= image_tag("服務流程信用卡圖.png", :alt => "不忙按摩")%>
          <h3>3. 付款，完成預約</h3>
          <p>送出預約需求後進行付款，即可完成預約。</p>
        </div>

        <div class="col-md-3">
          <%= image_tag("服務流程愛心圖.png", :alt => "不忙按摩")%>
          <h3>4. 享受服務</h3>
          <p>專業的按摩師會準時前往服務，讓團隊每個人都能享有一段放鬆的時光！</p>
        </div>
      </div>
    </div>
  </div>
</div>


<div id="story">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="slogan">
          <h2>Best service for best employee.</h2>
        </div>

        <div class="slogan-link">
          <a href="http://homepage.unbusymassage.tech/bookings/new" class="button">立即預約</a>
        </div>
      </div>
    </div>
  </div>
</div>